### ISSUE TITLE
Regexp issues

### ISSUE THREAD

**Issue by hkucharek** [glidernet/ogn-commons-java#2]
I'm doing some own java stuff and when I found this code, I recognized a few differences between the regexps here and mine.

1) In basicAprsPattern is the part /A=(\\\\d{6})
When bombing my similar first pattern, it failed with a sentence:
ICACFC7C5>APRS,qAS,KalkarESP:/235413h5144.77N/00616.69E'000/000/A=-00059 !W96! id3DCFC7C5 +000fpm +0.0rot 32.0dB 0e -0.0kHz
/A=(\\\\d{6}) fails for two reasons: The sign and because now it is only 5 digits.
My pattern part is /A=(-?\\\\d{5,6}) Maybe the even more tolerant /A=(-?\\\\d+) should be used.

2) "(\\\\+|\\\\-)(\\\\d+\\\\.\\\\d+)rot"
```
turnRate = Float.parseFloat(matcher.group(2));
if (matcher.group(1).equals("-"))
   turnRate *= -1;
```

Why explicitely dealing with the sign? Why not simply do:
"([+-]\\\\d+\\\\.\\\\d+)rot"
turnRate = Float.parseFloat(matcher.group(1));
Also using "[+-]" in place of "(\\\\+|\\\\-)" makes the regexp a bit more readable. Is it really necessary to use escapes in "(\\\\+|\\\\-)"?
Explicitely dealing with the sign is in a few more places. Do I miss something?

3) Turn rate 1.0 rot is 360° in 120s, that means 1.0 rot is 3°/s.

Comment in code is:
```
/**
* turn rate in deg/s
*/
protected float turnRate;
```

So, maybe in 2) it should be turnRate = Float.parseFloat(matcher.group(2)) * 3.0;

**Comment by wbuczak** [comment]
Thanks for your feedback! I will try to improve it according to your remarks!

**Comment by wbuczak** [comment]
Hi

Following your comment, I've updated regexp'es in the AprsAircraftBeacon and AprsReceiverBeacon classes:

https://github.com/glidernet/ogn-commons-java/commit/69b8bd5f14806fb242f5a2ee4dbc3f5cebae561f

Thanks!
Regards
Wojtek
